### PR TITLE
Try/Except blocks and fixes to float input

### PR DESCRIPTION
**Pull request by AKH1507**
Added try/except blocks and removed the extra space on the bottom of the float input

### CODE REVIEW

**Comment by AvirajB21E** [comment]
add it in includes/python_modals.html

**Comment by AvirajB21E** [comment]
the code u need to copy and paste one of them and replace the modal name with urs

**Comment by AKH1507** [comment]
Yh I did that already

**Comment by AvirajB21E** [comment]
mate ive just told you to do it

**Comment by AvirajB21E** [comment]
i can see you just added it I HATE liars

**Comment by bitFez** [comment]
guys, can I share this dialogue between you both?
Firstly, it's hilarious 😂
secondly, it gave me an idea for what we should do next to make sure that we can see changes made by others.

**Comment by AvirajB21E** [comment]
Sure sir

**Comment by AKH1507** [comment]
Sure sir that's fine

**Comment by AKH1507** [comment]
> i can see you just added it I HATE liars

Right what are you typing about

**Comment by AvirajB21E** [comment]
what are YOU typing about

**Comment by AKH1507** [comment]
Pls just stop I rlly hate liars

**Comment by AKH1507** [comment]
Right remove that thumbs down right now

**Pull request closed without merging**
